name: Run tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.6'
          - '1.7'
          - '1.8'
          - 'nightly'
        julia-arch:
          - x64
        os:
          - ubuntu-latest
        include:
          # Reduce the number of macOS jobs, as fewer can be run in parallel
          - os: macos-latest
            julia-version: '1.6'
          - os: macos-latest
            julia-version: '1.8'

    steps:
      - uses: actions/checkout@v2
        with:
          # For Codecov, we must also fetch the parent of the HEAD commit to
          # be able to properly deal with PRs / merges
          fetch-depth: 2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@latest
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest
      - name: "Run doctests"
        # we run the doctests here, too, to get code coverage from them;
        # but only do it in one Julia version, to avoid annoyance caused by
        # difference in the outputs between Julia versions
        if: ${{ matrix.julia-version == '1.5' }}
        run: |
          julia --project=docs --color=yes --code-coverage -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            using Documenter: doctest
            using JuLie
            doctest(JuLie)'
      - name: "Process code coverage"
        uses: julia-actions/julia-processcoverage@v1
      - name: "Upload coverage data to Codecov"
        continue-on-error: true
        uses: codecov/codecov-action@v2
